export const NATIONALITIES = {
  US: { name: "American", color: "gray" },
  AU: { name: "Australian", color: "gray" },
  BR: { name: "Brazilian", color: "gray" },
  GB: { name: "British", color: "gray" },
  CA: { name: "Canadian", color: "gray" },
  DK: { name: "Danish", color: "gray" },
  NL: { name: "Dutch", color: "gray" },
  FI: { name: "Finnish", color: "gray" },
  FR: { name: "Franch", color: "gray" },
  DE: { name: "German", color: "gray" },
  IR: { name: "Iranian", color: "gray" },
  IE: { name: "Irish", color: "gray" },
  NZ: { name: "New Zealander", color: "gray" },
  NO: { name: "Norwegian", color: "gray" },
  ES: { name: "Spanish", color: "green" },
  CH: { name: "Swiss", color: "gray" },
  TR: { name: "Turkish", color: "gray" },
  UNKNOWN: { name: "Unknown", color: "gray" },
};
