export const NATIONALITIES = {
  // US: "American",
  // AU: "Australian",
  // BR: "Brazilian",
  // GB: "British",
  // CA: "Canadian",
  // DK: "Danish",
  // NL: "Dutch",
  // FI: "Finnish",
  // FR: "Franch",
  // DE: "German",
  // IR: "Iranian",
  // IE: "Irish",
  // NZ: "New Zealander",
  // NO: "Norwegian",
  ES: { name: "Spanish", color: "green" },
  UNKNOWN: { name: "Unknown", color: "gray" },
  // CH: "Swiss",
  // TR: "Turkish",
};
