export const NATIONALITIES = {
  US: { name: "American", color: "default" },
  AU: { name: "Australian", color: "magenta" },
  BR: { name: "Brazilian", color: "red" },
  GB: { name: "British", color: "geekblue" },
  CA: { name: "Canadian", color: "volcano" },
  DK: { name: "Danish", color: "lime" },
  NL: { name: "Dutch", color: "rgb(135, 208, 104)" },
  FI: { name: "Finnish", color: "cyan" },
  FR: { name: "French", color: "blue" },
  DE: { name: "German", color: "gold" },
  IR: { name: "Iranian", color: "rgb(255, 85, 0)" },
  IE: { name: "Irish", color: "purple" },
  NZ: { name: "New Zealander", color: "rgb(158, 16, 104)" },
  NO: { name: "Norwegian", color: "rgb(45, 183, 245)" },
  ES: { name: "Spanish", color: "green" },
  CH: { name: "Swiss", color: "orange" },
  TR: { name: "Turkish", color: "rgb(255, 214, 102)" },
  UNKNOWN: { name: "Unknown", color: "gray" },
};
